on: [ push ]

jobs:
  migration_job:
    runs-on: ubuntu-latest
    name: CI migration
    steps:
      # Checkout the source code
      - name: Checkout
        uses: actions/checkout@v2

      # Run the migration with Postgres.ai Action
      - name: DB migration with DLE
        uses: agneum/migration-action@v0.0.10
        id: db-migration
        with:
          dbname: test
          commands: |
            rails db:migrate
            echo 'Forward migration completed successfully.'

            rails db:rollback
            echo 'Rollback complete successfully.'
          migration_envs: |
            DATABASE_LAB_CI=true
          download_artifacts: true
        env:
          CI_ENDPOINT: ${{ secrets.CI_ENDPOINT }}
          SECRET_TOKEN: ${{ secrets.SECRET_TOKEN }}

      # Download artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: artifacts
          path: artifacts/*
          if-no-files-found: ignore
        if: always()

      # Show migration summary
      - name: Get the response status
        run: echo "${{ steps.db-migration.outputs.response }}"
